baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'EVOPS'
theme = "universal"
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params]
    style = "default"
    viewMorePostLink = "/datasets/"
    date_format = "January 2, 2006"
    disabled_logo = true
    logo_text = "EVOPS"
    about_us = "<p>Jarosh Dmitriy</p> <p>Kornilova Anastasiia</p> <p>Polosatik ????</p> <p>Mokeev Pavel</p> <p>Tojiboev Fakhriddin</p>"

    contact_url = "/paper/"
    address = """<p class="text-uppercase"><strong>Mobile Robotics Lab. at Skoltech </strong>
            <strong>Russia</strong>
          </p>
          """

[permalinks]
    datasets = "/datasets/:year/:month/:day/:filename/"

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Datasets"
    identifier = "menu.datasets"
    url        = "/datasets/"
    weight     = 2

[[menu.main]]
    name       = "Metrics"
    identifier = "menu.metrics"
    url        = "/metrics/"
    weight     = 3

[[menu.main]]
    name       = "Evaluation"
    identifier = "menu.evaluation"
    url        = "/evaluation/"
    weight     = 4

[[menu.main]]
    name       = "Paper"
    identifier = "menu.paper"
    url        = "/paper/"
    weight     = 5

[params.features]
    enable = true
    cols = 3

[params.footer.recent_posts]
    enable = false

[params.widgets]
    categories = true
    tags = true